namespace Models.Heroes.HeroCharacteristics
{
    public enum TypeCharacteristic
    {
        Damage,
        HP,
        Defense,
        Initiative,
        Attack,
        ProbabilityCriticalAttack,
        DamageCriticalAttack,
        Accuracy,
        CleanDamage,
        Dodge,
        MagicResistance,
        CritResistance,
        PoisonResistance,
        StunResistance,
        PetrificationResistance,
        FreezingResistance,
        AstralResistance,
        DumbResistance,
        SilinceResistance,
        EfficiencyHeal,
        Speed,
        CountTargetForSimpleAttack,
        CountTargetForSpell
    }
}
